name: Run tests

on:
  workflow_call:
    inputs:
      package:
        description: api | chromium
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: TeamCity Setup
        uses: ./.github/actions/teamcity-setup/

      - name: Run tests
        continue-on-error: false
        run: | 
          yarn playwright test --config=api.config.ts --project=${{ inputs.package }}