name: Deploy backend

on: workflow_call

#it is just example

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend
        run: echo run build, start unit tests, create and push new docker image

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to stage
        run: echo Deploy